<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gr1616" nsURI="platform:/plugin/tdt4250.gr16nn.model/model/gr1616.ecore"
    nsPrefix="gr1616">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" upperBound="-1" eType="#//Game"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//ItemType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minions" upperBound="-1"
        eType="#//Minion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Locations" eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eOperations name="getNearby" eType="ecore:EClass ../../../no.hal.pgo.osm/model/osm.ecore#//GeoLocated">
      <eParameters name="player" eType="#//Player"/>
    </eOperations>
    <eOperations name="playerPickItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="player" eType="#//Player"/>
      <eParameters name="item" eType="#//Item"/>
      <eParameters name="onlyCheck" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="playerVsPlayer" eType="#//Player">
      <eParameters name="p1" eType="#//Player"/>
      <eParameters name="p2" eType="#//Player"/>
    </eOperations>
    <eOperations name="playerVsMinion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ids" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="../../../no.hal.pgo.osm/model/osm.ecore#//GeoLocated">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//AbleToHold"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass ../../../no.hal.pgo.osm/model/osm.ecore#//GeoLocated"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemType" eType="#//ItemType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemType" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PotionClass" eSuperTypes="#//ItemType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArmorClass" eSuperTypes="#//ItemType"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeaponClass" eSuperTypes="#//ItemType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Weapon"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyClass" eSuperTypes="#//ItemType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Weapon"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Key"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Armor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Potion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="../../../no.hal.pgo.osm/model/osm.ecore#//GeoLocated">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceType" eType="#//InstanceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" abstract="true" interface="true"
      eSuperTypes="../../../no.hal.pgo.osm/model/osm.ecore#//GeoLocation #//AbleToHold">
    <eOperations name="getRaceGoodAgainst" eType="#//Player"/>
    <eOperations name="getAffraidOf" eType="#//Minion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickname" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xp" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeWeapon" eType="#//WeaponClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeArmor" eType="#//ArmorClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DarkElf" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="Human" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="Orc" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dwarf" eSuperTypes="#//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minion" eSuperTypes="../../../no.hal.pgo.osm/model/osm.ecore#//GeoLocation #//AbleToHold">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hp" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attack" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GreatSpider" eSuperTypes="#//Minion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wizzard" eSuperTypes="#//Minion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ent" eSuperTypes="#//Minion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Warg" eSuperTypes="#//Minion"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbleToHold" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventory" upperBound="-1"
        eType="#//Item"/>
  </eClassifiers>
</ecore:EPackage>
